/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_h01c_pridjecore_PridJeCoreEntry */

#ifndef _Included_pers_h01c_pridjecore_PridJeCoreEntry
#define _Included_pers_h01c_pridjecore_PridJeCoreEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_h01c_pridjecore_PridJeCoreEntry
 * Method:    InitPridJeCore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pers_h01c_pridjecore_PridJeCoreEntry_InitPridJeCore
  (JNIEnv *, jobject);

/*
 * Class:     pers_h01c_pridjecore_PridJeCoreEntry
 * Method:    UnInitPridJeCore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pers_h01c_pridjecore_PridJeCoreEntry_UnInitPridJeCore
  (JNIEnv *, jobject);

/*
 * Class:     pers_h01c_pridjecore_PridJeCoreEntry
 * Method:    ProcessFunction
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_h01c_pridjecore_PridJeCoreEntry_ProcessFunction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
